---

sudo: required

dist: trusty

language: php

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION = '5.6' ]; then echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - composer self-update
  - composer global require --no-update hirak/prestissimo:@stable
  - composer global update

install:
  - composer update
  - npm update
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/drupal site:install drustack --yes --no-interaction --db-type="sqlite" --db-file="sites/default/files/.ht.sqlite"
  - php -S 127.0.0.1:8080 -t . >/dev/null 2>&1 &

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/phpunit -c core --testsuite unit --group Drupal

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm
