---

sudo: required

dist: trusty

language: php

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != hhvm ]; then phpenv config-rm xdebug.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != hhvm ]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - composer self-update
  - composer global require --no-update hirak/prestissimo:@stable
  - composer global update

install:
  - composer update
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/drush --yes site-install drustack --db-url=sqlite://sites/default/files/.ht.sqlite
  - php -S 127.0.0.1:8080 -t . >/dev/null 2>&1 &

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/drush --yes pm-enable simpletest
  - php ./scripts/run-tests.sh --php `which php` --url http://127.0.0.1:8080 --concurrency 8 --class InfoFileParserTestCase

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: hhvm
  allow_failures:
    - php: hhvm
