---

sudo: false

dist: trusty

language: php

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

scripts:
  - echo 0;
