---

sudo: false

dist: trusty

language: php

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION = '5.6' ]; then echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - travis_retry composer -n self-update
  - travis_retry composer -n global require --no-update consolidation/cgr:@stable
  - travis_retry composer -n global require --no-update hirak/prestissimo:@stable
  - travis_retry composer -n global update
  - export PATH="$HOME/.composer -n/vendor/bin:$PATH"
  - travis_retry cgr -n drupal/console ~1.0 --stability RC
  - travis_retry cgr -n drush/drush ~8.0
  - travis_retry cgr -n phpunit/phpunit ~5.7

install:
  - travis_retry composer -n update
  - travis_retry npm update
  - cd $TRAVIS_BUILD_DIR/web
  - drush site-install drustack --yes --db-url=sqlite://sites/default/files/.ht.sqlite
  - php -S 127.0.0.1:8080 -t . >/dev/null 2>&1 &

script:
  - cd $TRAVIS_BUILD_DIR
  - phpunit -c phpunit.xml.dist --testsuite unit --group Drupal

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm
