---

sudo: required

dist: trusty

language: php

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require --no-update hirak/prestissimo:@stable
  - composer global update

install:
  - composer update
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/drush --yes site-install drustack --db-url=sqlite://sites/default/files/.ht.sqlite
  - php -S 127.0.0.1:8080 -t . >/dev/null 2>&1 &

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ../vendor/bin/phpunit -c core --testsuite unit --group Drupal

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: hhvm
