---

sudo: false

dist: trusty

language: php

before_install:
  - composer self-update
  - composer global require --no-update drush/drush:@stable
  - composer global require --no-update phpunit/phpunit:@stable
  - composer global update
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer update
  - drush site-install testing --yes --db-url=sqlite://sites/default/files/.ht.sqlite
  - drush runserver http://127.0.0.1:8080 &

script:
  - phpunit -c core --testsuite unit --exclude-group Composer
